version: "3"

volumes:
  rabbitmq_data:

services:

  ###################################
  # 1 : The Cart microservice
  ###################################
  cart:
    build:
      context: ./
      dockerfile: cart.Dockerfile
    container_name: cart
    restart: always
    environment:
      dbURL:
      PYTHONUNBUFFERED: 1
    ports:
      - '5100:5100'
    networks:
      - CMEnetwork

  ###################################
  # 2 : The Item microservice
  ###################################
  item:
    build:
      context: ./
      dockerfile: item.Dockerfile
    container_name: item
    restart: always
    environment:
      dbURL: 
      PYTHONUNBUFFERED: 1
    ports:
      - '5200:5200'
    networks:
      - CMEnetwork

  ###################################
  # 3: The Order microservice
  ###################################
  order:
    build:
      context: ./
      dockerfile: order.Dockerfile
    container_name: order
    restart: always
    environment:
      dbURL: 
      PYTHONUNBUFFERED: 1
    ports:
      - '5300:5300'
    networks:
      - CMEnetwork

  ###################################
  # 4: The User microservice
  ###################################
  user:
    build:
      context: ./
      dockerfile: user.Dockerfile
    container_name: user
    restart: always
    environment:
      dbURL: 
      PYTHONUNBUFFERED: 1
    ports:
      - '5400:5400'
    networks:
      - CMEnetwork

  ###################################
  # 5: The Payment service
  ###################################
  payment:
    build:
      context: ./
      dockerfile: payment.Dockerfile
    container_name: payment
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - '5500:5500'
    networks:
      - CMEnetwork

  ###############################################
  # 6: The Place Order microservice
  ###############################################
  place_order:
    build:
      context: ./
      dockerfile: place_order.Dockerfile
    container_name: place_order
    restart: always
    depends_on:
      - "item"
      - "order"
      - "user"
    environment:
      order_URL: http://order:5002/order
      item_URL: http://item:5001/item/increase-count 
      payment_URL: http://payment:5004/payment
      user_URL: http://user:5003/user/details
      PYTHONUNBUFFERED: 1
    ports:
      - "5600:5600"
    networks:
      - CMEnetwork

networks:
  CMEnetwork:
    driver: 