DROP DATABASE IF EXISTS G4TF_activity_logs;
DROP DATABASE IF EXISTS G4TF_items;
DROP DATABASE IF EXISTS G4TF_orders;
DROP DATABASE IF EXISTS G4TF_users;

CREATE DATABASE G4TF_activity_logs;
CREATE DATABASE G4TF_items;
CREATE DATABASE G4TF_orders;
CREATE DATABASE G4TF_users;

CREATE USER 'G4TFUser'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'G4TFUser'@'%' WITH GRANT OPTION;
ALTER USER 'G4TFUser'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;